// Runtime validation for data loaded from cities.json and per-city road
// JSONs. Both come from external sources now (cities.json is bundled but
// generated by scripts/extract-urban-areas.js; roads are fetched from the
// sibling repo's GitHub Pages site). Validation catches malformed files
// before they crash render code that assumes well-shaped data.
//
// Schemas are intentionally `.strip()` (default) — unknown keys are dropped
// silently rather than rejected, so pipeline emitting new fields doesn't
// break the app. Required-key violations and type mismatches do error.

import { z } from 'zod';

const RegionSchema = z.enum([
  'china', 'asia', 'europe', 'north-america', 'south-america', 'africa',
]);

// GeoJSON Position is [lng, lat]; may include altitude as a 3rd number.
// Allow either shape.
const PositionSchema = z.array(z.number()).min(2).max(3);

// LinearRing — a closed sequence of positions, ≥4 entries (per GeoJSON
// spec a polygon ring must close: first == last). We don't enforce
// closure here; just minimum 4 entries to catch obviously empty rings.
const LinearRingSchema = z.array(PositionSchema).min(4);

const PolygonSchema = z.object({
  type: z.literal('Polygon'),
  coordinates: z.array(LinearRingSchema).min(1),
});

const MultiPolygonSchema = z.object({
  type: z.literal('MultiPolygon'),
  coordinates: z.array(z.array(LinearRingSchema).min(1)).min(1),
});

const GeometrySchema = z.union([PolygonSchema, MultiPolygonSchema]);

const BboxSchema = z.tuple([z.number(), z.number(), z.number(), z.number()]);

export const CityDataSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  nameZh: z.string().min(1),
  country: z.string().min(1),
  region: RegionSchema,
  geojson: GeometrySchema,
  bbox: BboxSchema,
  areaKm2: z.number().positive(),
});

export const CitiesArraySchema = z.array(CityDataSchema);

// Roads file format: array of polylines, each polyline an array of
// [lng, lat] pairs. We validate the structural shape (3 levels of
// nested arrays of numbers) but skip per-coordinate range checks for
// performance — Tokyo's stitched roads have ~250k vertices.
export const RoadsSchema = z.array(
  z.array(z.array(z.number()).min(2)).min(2)
);

// Helper: turn a Zod ZodError into a short human-readable string for
// toast/error messages. Default error format is verbose and JSONy.
export function formatZodError(err: z.ZodError): string {
  const issues = err.issues.slice(0, 3); // cap at 3 to keep toasts short
  const lines = issues.map((i) => `${i.path.join('.') || '<root>'}: ${i.message}`);
  if (err.issues.length > 3) {
    lines.push(`… (+${err.issues.length - 3} more)`);
  }
  return lines.join('; ');
}
